POINTS_PER_RECEPTION = 0.5
POINTS_PER_FIRST_DOWN = 0.5

POINTS_PER_PASS_TD = 6.0
POINTS_PER_PASS_YD = 0.04
POINTS_PER_PASS_INT = -2.0

POINTS_PER_REC_YD = 0.1
POINTS_PER_REC_TD = 6.0
POINTS_PER_RUSH_YD = 0.1
POINTS_PER_RUSH_TD = 6.0

POINTS_PER_FUMBLE_LOST = -2.0

FOOTBALL_REFERENCE_YEAR = 2021